import type { Pet } from "@/app/components/landing/PetDetail";

export const SAMPLE_PETS: Pet[] = [
  { id: 1, name: "Bella", species: "Dog", breed: "Golden Retriever", age: "2 years", gender: "Female", status: "Available", adoptionFee: 3500, image: "https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&h=300&fit=crop&auto=format", vaccinated: true, neutered: true, temperament: ["Friendly", "Gentle", "Playful"], description: "Bella is a sweet and gentle Golden Retriever who loves playing fetch and cuddling. She is great with kids and other dogs.", requirements: ["Valid ID and proof of residence", "Secure fenced yard recommended", "All family members must agree"], customQuestions: ["How many hours a day will Bella be alone?", "Do you have experience with large breeds?"] },
  { id: 2, name: "Max", species: "Dog", breed: "Labrador", age: "3 years", gender: "Male", status: "Available", adoptionFee: 3000, image: "https://images.unsplash.com/photo-1561037404-61cd46762b07?w=400&h=300&fit=crop&auto=format", vaccinated: true, neutered: true, temperament: ["Energetic", "Loyal", "Friendly"], description: "Max is a high-energy Labrador who loves outdoor activities. He is well-trained and responds to basic commands.", requirements: ["Active lifestyle required", "Secure fenced yard", "Commitment to daily exercise"], customQuestions: ["What is your daily exercise routine?", "Have you owned an active breed before?"] },
  { id: 3, name: "Luna", species: "Cat", breed: "Siamese", age: "1 year", gender: "Female", status: "Available", adoptionFee: 2000, image: "https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400&h=300&fit=crop&auto=format", vaccinated: true, neutered: false, temperament: ["Curious", "Independent", "Gentle"], description: "Luna is an elegant Siamese cat with a playful yet independent personality. She enjoys high perches and interactive toys.", requirements: ["Indoor-only home", "Cat tree or shelves recommended", "No other aggressive pets"], customQuestions: ["Do you have experience with cats?", "Will Luna be an indoor-only cat?"] },
  { id: 4, name: "Charlie", species: "Cat", breed: "Persian", age: "4 years", gender: "Male", status: "Available", adoptionFee: 2500, image: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=400&h=300&fit=crop&auto=format", vaccinated: true, neutered: true, temperament: ["Calm", "Gentle", "Friendly"], description: "Charlie is a laid-back Persian cat who loves being petted and sitting on laps. He is perfect for a quiet home.", requirements: ["Grooming commitment (daily brushing)", "Quiet home environment preferred", "Regular vet check-ups"], customQuestions: ["Are you experienced with long-haired breeds?", "How often can you groom Charlie?"] },
  { id: 5, name: "Daisy", species: "Rabbit", breed: "Holland Lop", age: "1 year", gender: "Female", status: "Available", adoptionFee: 1500, image: "https://images.unsplash.com/photo-1585110396063-83568f6f357b?w=400&h=300&fit=crop&auto=format", vaccinated: true, neutered: true, temperament: ["Friendly", "Calm", "Shy"], description: "Daisy is an adorable Holland Lop rabbit with floppy ears. She is shy at first but warms up quickly.", requirements: ["Spacious cage with exercise area", "Fresh hay and vegetables daily", "Gentle handling only"], customQuestions: ["Have you owned a rabbit before?", "Do you have a quiet space for Daisy?"] },
  { id: 6, name: "Kiwi", species: "Bird", breed: "Cockatiel", age: "2 years", gender: "Male", status: "Available", adoptionFee: 2000, image: "https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&h=300&fit=crop&auto=format", vaccinated: true, neutered: true, temperament: ["Playful", "Curious", "Intelligent"], description: "Kiwi is a charming cockatiel who loves to whistle and mimic sounds. He enjoys interaction and can learn tricks.", requirements: ["Large bird cage minimum", "Daily out-of-cage time", "Social interaction several hours daily"], customQuestions: ["Do you have experience with birds?", "How much time can you spend with Kiwi daily?"] },
  { id: 7, name: "Rocky", species: "Dog", breed: "German Shepherd", age: "5 years", gender: "Male", status: "Available", adoptionFee: 3000, image: "https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400&h=300&fit=crop&auto=format", vaccinated: true, neutered: true, temperament: ["Loyal", "Energetic", "Intelligent"], description: "Rocky is a loyal and intelligent German Shepherd. He is well-trained and makes an excellent guard dog and companion.", requirements: ["Experienced dog owner required", "Large secure yard", "Daily physical and mental exercise"], customQuestions: ["Have you handled working breeds before?", "Can you provide a secure outdoor space?"] },
  { id: 8, name: "Milo", species: "Cat", breed: "Tabby", age: "6 months", gender: "Male", status: "Available", adoptionFee: 1500, image: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=400&h=300&fit=crop&auto=format", vaccinated: true, neutered: false, temperament: ["Playful", "Curious", "Friendly"], description: "Milo is a playful kitten who loves to explore and pounce on toys. He is still growing and needs a loving home.", requirements: ["Kitten-proofed home", "Interactive toys and scratching posts", "Commitment to neutering"], customQuestions: ["Have you raised a kitten before?", "Are you prepared for the neutering procedure?"] },
];

export function getPetById(id: number): Pet | undefined {
  return SAMPLE_PETS.find((pet) => pet.id === id);
}
